name: smartsheba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  http: ^1.2.3
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  permission_handler: ^11.3.1 # Added for file access permissions
  uuid: ^4.4.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  lottie: ^2.7.0 
  flutter_rating_bar: ^4.0.1
  geolocator: ^11.0.1  # Permissions and position (battery-optimized).
  geocoding: ^2.1.1  # Address search/reverse.
  google_maps_flutter: ^2.5.0  # Static map embed.
  dartz: ^0.10.1
  get_it: ^7.6.4
  badges: ^3.1.1
  speech_to_text: ^7.0.0
  rxdart: ^0.27.7
  # ... your existing dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_photo.jpg
    - assets/icons/
